# Site settings
#title: Giancarlo Visconti
#email: giancarlo.visconti@columbia.edu
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Build settings
markdown: kramdown
theme: minima

# needed for CI builds:
exclude: [vendor]
