# Site settings
title: Giancarlo Visconti
email: giancarlo.visconti@columbia.edu
description: "I'm a PhD Candidate in the Department of Government at Columbia University. I study comparative political behavior, and methods."
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://giancarlovisconti.com" # the base hostname & protocol for your site
enforce_ssl: giancarlovisconti.com
github_username:  giancarlovisconti
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Build settings
markdown: kramdown
theme: minima
disqus:
  shortname: gvisconti

# needed for CI builds:
exclude: [vendor]
